/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#0e1320',
        'surface-dim': '#0e1320',
        'surface-bright': '#343948',
        'surface-container-lowest': '#090e1b',
        'surface-container-low': '#161b29',
        'surface-container': '#1a1f2d',
        'surface-container-high': '#252a38',
        'surface-container-highest': '#303443',
        surface: '#0e1320',
        'surface-variant': '#303443',
        'on-surface': '#dee2f5',
        'on-surface-variant': '#c2c6d6',
        'inverse-surface': '#dee2f5',
        'inverse-on-surface': '#2b303e',
        outline: '#8c909f',
        'outline-variant': '#424754',
        'surface-tint': '#adc6ff',
        primary: '#adc6ff',
        'on-primary': '#002e6a',
        'primary-container': '#4d8eff',
        'on-primary-container': '#00285d',
        'inverse-primary': '#005ac2',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        secondary: '#4cd7f6',
        'on-secondary': '#003640',
        'secondary-container': '#03b5d3',
        'on-secondary-container': '#00424e',
        'secondary-fixed': '#acedff',
        'secondary-fixed-dim': '#4cd7f6',
        'on-secondary-fixed': '#001f26',
        'on-secondary-fixed-variant': '#004e5c',
        tertiary: '#4edea3',
        'on-tertiary': '#003824',
        'tertiary-container': '#00a572',
        'on-tertiary-container': '#00311f',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'on-background': '#dee2f5',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1rem',
        'gutter-mobile': '0.75rem',
        margin: '1rem',
        'margin-safe-top': 'env(safe-area-inset-top, 1rem)',
        'margin-safe-bottom': 'env(safe-area-inset-bottom, 1.25rem)',
        'space-2xs': '0.25rem',
        'space-xs': '0.375rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '2.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        display: ['34px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-sm': ['17px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'tabular-amount': ['20px', { lineHeight: '24px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
