package com.receipttrust.notification;

public enum NotificationType {
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    DEBT_CREATED,
    PAYMENT_SUBMITTED,
    PAYMENT_APPROVED,
    PAYMENT_REJECTED,
    DEBT_SETTLED,
    DEBT_MARKED_PAID,
    DEBT_COMMENT,
    ASSIGNMENT_CONFIRM_REQUEST,
    ASSIGNMENT_CONFIRMED,
    ASSIGNMENT_DECLINED,
    DIRECT_MESSAGE
}
