-- ReceiptTrust initial schema

CREATE TABLE users (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name          VARCHAR(255)   NOT NULL,
    username           VARCHAR(255)   NOT NULL,
    email              VARCHAR(255)   NOT NULL,
    password_hash      VARCHAR(255)   NOT NULL,
    profile_image_path VARCHAR(512),
    trust_score        INTEGER        NOT NULL DEFAULT 500,
    created_at         TIMESTAMPTZ    NOT NULL,
    updated_at         TIMESTAMPTZ    NOT NULL,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id),
    token       VARCHAR(512) NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_refresh_tokens_token UNIQUE (token)
);

CREATE TABLE friendships (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT      NOT NULL REFERENCES users (id),
    addressee_id BIGINT      NOT NULL REFERENCES users (id),
    status       VARCHAR(20) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_friendship_pair UNIQUE (requester_id, addressee_id)
);

CREATE TABLE receipts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id           BIGINT       NOT NULL REFERENCES users (id),
    store_name         VARCHAR(255) NOT NULL,
    purchase_date      DATE         NOT NULL,
    notes              TEXT,
    image_path         VARCHAR(512) NOT NULL,
    image_content_type VARCHAR(100) NOT NULL,
    finalized          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ  NOT NULL,
    updated_at         TIMESTAMPTZ  NOT NULL
);

CREATE TABLE receipt_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id  BIGINT         NOT NULL REFERENCES receipts (id),
    name        VARCHAR(255)   NOT NULL,
    quantity    INTEGER        NOT NULL,
    unit_price  NUMERIC(12, 2) NOT NULL,
    line_total  NUMERIC(12, 2) NOT NULL,
    created_at  TIMESTAMPTZ    NOT NULL,
    updated_at  TIMESTAMPTZ    NOT NULL
);

CREATE TABLE item_assignments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_item_id BIGINT         NOT NULL REFERENCES receipt_items (id),
    assignee_id     BIGINT         NOT NULL REFERENCES users (id),
    split_type      VARCHAR(20)    NOT NULL,
    share_amount    NUMERIC(12, 2) NOT NULL,
    created_at      TIMESTAMPTZ    NOT NULL,
    updated_at      TIMESTAMPTZ    NOT NULL
);

CREATE TABLE debts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creditor_id        BIGINT         NOT NULL REFERENCES users (id),
    debtor_id          BIGINT         NOT NULL REFERENCES users (id),
    receipt_id         BIGINT         NOT NULL REFERENCES receipts (id),
    purchase_date      DATE           NOT NULL,
    due_date           DATE           NOT NULL,
    original_amount    NUMERIC(12, 2) NOT NULL,
    outstanding_amount NUMERIC(12, 2) NOT NULL,
    status             VARCHAR(20)    NOT NULL,
    settled_at         TIMESTAMPTZ,
    overdue_penalized  BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ    NOT NULL,
    updated_at         TIMESTAMPTZ    NOT NULL
);

CREATE TABLE debt_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_id    BIGINT         NOT NULL REFERENCES debts (id),
    item_name  VARCHAR(255)   NOT NULL,
    amount     NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMPTZ    NOT NULL,
    updated_at TIMESTAMPTZ    NOT NULL
);

CREATE TABLE payments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_id       BIGINT         NOT NULL REFERENCES debts (id),
    submitter_id  BIGINT         NOT NULL REFERENCES users (id),
    amount        NUMERIC(12, 2) NOT NULL,
    method        VARCHAR(20)    NOT NULL,
    notes         TEXT,
    status        VARCHAR(20)    NOT NULL,
    balance_after NUMERIC(12, 2),
    decided_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ    NOT NULL,
    updated_at    TIMESTAMPTZ    NOT NULL
);

CREATE TABLE trust_score_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL REFERENCES users (id),
    delta           INTEGER     NOT NULL,
    reason          VARCHAR(255) NOT NULL,
    resulting_score INTEGER     NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    type       VARCHAR(40)  NOT NULL,
    message    VARCHAR(500) NOT NULL,
    is_read    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_receipts_owner ON receipts (owner_id);
CREATE INDEX idx_receipt_items_receipt ON receipt_items (receipt_id);
CREATE INDEX idx_item_assignments_item ON item_assignments (receipt_item_id);
CREATE INDEX idx_debts_creditor ON debts (creditor_id);
CREATE INDEX idx_debts_debtor ON debts (debtor_id);
CREATE INDEX idx_debts_receipt ON debts (receipt_id);
CREATE INDEX idx_payments_debt ON payments (debt_id);
CREATE INDEX idx_notifications_user ON notifications (user_id);
CREATE INDEX idx_trust_events_user ON trust_score_events (user_id);
