-- Comments on debts for creditor/debtor communication.
CREATE TABLE debt_comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_id    BIGINT       NOT NULL REFERENCES debts (id),
    author_id  BIGINT       NOT NULL REFERENCES users (id),
    body       VARCHAR(1000) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_debt_comments_debt ON debt_comments (debt_id);
