-- Direct messages between accepted friends.
CREATE TABLE direct_messages (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id          BIGINT        NOT NULL REFERENCES users (id),
    recipient_id       BIGINT        NOT NULL REFERENCES users (id),
    body               VARCHAR(2000) NOT NULL,
    read_by_recipient  BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ   NOT NULL,
    updated_at         TIMESTAMPTZ   NOT NULL
);

-- Fast lookup of a conversation in either direction, and of unread counts.
CREATE INDEX idx_dm_sender_recipient ON direct_messages (sender_id, recipient_id);
CREATE INDEX idx_dm_recipient_unread ON direct_messages (recipient_id, read_by_recipient);
