-- Global OCR learning vocabulary: confirmed store and item names captured when
-- users finalize receipts. Future OCR reads are fuzzy-matched against these so
-- parsing improves as more receipts are confirmed. Global (shared by all users).

CREATE TABLE ocr_terms (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 'STORE' or 'ITEM'
    kind        VARCHAR(10)  NOT NULL,
    -- Canonical display text as confirmed by a user.
    text        VARCHAR(200) NOT NULL,
    -- Lowercased, punctuation/space-collapsed form for matching + uniqueness.
    normalized  VARCHAR(200) NOT NULL,
    -- How many times this term has been confirmed (higher = more trusted).
    occurrences INTEGER      NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_ocr_terms_kind_norm UNIQUE (kind, normalized)
);

CREATE INDEX idx_ocr_terms_kind ON ocr_terms (kind);
